### ISSUE TITLE
Include alternatives / criticism of JWT?

### ISSUE THREAD

**Issue by jnv** [gitcommitshow/awesome-authentication#1]
Hi there! I drove by your repo to add it into my [lists](https://github.com/jnv/lists) repository and noticed that while the topic here is general authentication, it mostly focuses on JWT "for now". Would you be interested in covering criticisms of JWT as well, e.g. its poor design and usually improper use (like session tokens)?

Some resources on this topic:

- [Stop using JWT for sessions](http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/) and [part 2: Why your solution doesn't work](http://cryto.net/%7Ejoepie91/blog/2016/06/19/stop-using-jwt-for-sessions-part-2-why-your-solution-doesnt-work/)
- [Why JWTs Suck as Session Tokens](https://developer.okta.com/blog/2017/08/17/why-jwts-suck-as-session-tokens)
- [No Way, JOSE! Javascript Object Signing and Encryption is a Bad Standard That Everyone Should Avoid](https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid) (including JWT, JWE and JWS)
- https://github.com/shieldfy/API-Security-Checklist/issues/6 with more resources

And some alternatives:
- [Things to Use Instead of JWT](https://kevin.burke.dev/kevin/things-to-use-instead-of-jwt/)
- [Branca as an Alternative to JWT?](https://appelsiini.net/2017/branca-alternative-to-jwt/)
- [Paseto is a Secure Alternative to the JOSE Standards (JWT, etc.)](https://paragonie.com/blog/2018/03/paseto-platform-agnostic-security-tokens-is-secure-alternative-jose-standards-jwt-etc)

**Comment by gitcommitshow** [comment]
Thank you for contributing. I have added these links under _Security Risks and Criticism of JWT_ heading.

**Comment by jnv** [comment]
Thanks! I will go ahead and close this issue.
